<a href="https://colab.research.google.com/github/Gitstrong3333/Data-Science-Interview/blob/main/MachineLearning_Interview_Questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Please focus on learning Machine Learning. If you have worked on Python and Machine Learning projects, review the material regularly.

**I will be updating 5 questions daily based on the topics I study.**

# **Ace Your Upcoming Data Science Interview**

You may not be able to predict every question an interviewer will ask. However, you can prepare for many of the most important and frequently asked technical questions in advance.

This repository has been carefully curated to support your preparation for technical interview rounds. It is designed to strengthen your understanding of core data science concepts and help you confidently approach data science job opportunities.


Make sure you practice the examples given below—just 5 questions a day. Each day, revise the questions from the previous day along with the new ones. For example, on the second day you will review yesterday’s 5 questions plus today’s 5 questions (total 10). On the third day, revise those 10 questions again along with the new 5 questions for that day. By continuously practicing and revising in this way, you will strengthen your understanding of the concepts. If you are thorough with these questions, there is a strong chance that you can land a data engineering job.

# **Which function is commonly used to convert a multidimensional NumPy array into a one-dimensional array? If the resulting array is modified, will it affect the original array? Explain your answer.**

The flatten() function in NumPy is commonly used to convert a multidimensional array into a one-dimensional array.

The flatten() method returns a copy of the original array. Therefore, if you modify the flattened array, it will not affect the original array.

In [ ]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original Array:")
print(arr)

# Convert to 1D using flatten()
flat_arr = arr.flatten()

print("\nFlattened Array:")
print(flat_arr)

# Modify flattened array
flat_arr[0] = 100

print("\nModified Flattened Array:")
print(flat_arr)

print("\nOriginal Array After Modification:")
print(arr)

Original Array:
[[1 2 3]
 [4 5 6]]

Flattened Array:
[1 2 3 4 5 6]

Modified Flattened Array:
[100   2   3   4   5   6]

Original Array After Modification:
[[1 2 3]
 [4 5 6]]


# **2.If two variables are defined as a = 3 and b = 4, will the id() function return the same value for both variables? Explain your answer.**



Answer: Rewritten Answer

No, the id() function will not return the same value for a and b.

In Python, the id() function returns the unique identity of an object, which typically corresponds to its memory address. Since 3 and 4 are two different integer objects, they have different identities in memory. Therefore, id(a) and id(b) will return different values.

Each object in Python has a unique identity that remains constant during its lifetime.

In [ ]:
a = 3
b = 4

print(id(a))
print(id(b))

11654440
11654472


# **3.If two variables are defined as mean = 8 and Mean = 8, are they considered the same variable in Python? Explain your answer.**


No, mean and Mean are not considered the same variable in Python.

Python is a case-sensitive programming language, which means it treats uppercase and lowercase letters as different characters. Therefore, variable names that differ only in case are treated as completely separate variables.

Even though both variables store the same value (8), they are distinct identifiers in memory.

In [ ]:
mean = 8
Mean = 8

print(mean)
print(Mean)

8
8


Both will print 7, but they are two different variables.

# **4.What is the purpose of the inplace parameter in Pandas functions? Explain its behavior.**


The inplace parameter in Pandas functions determines whether a DataFrame is modified directly or a modified copy is returned.

When inplace=True, the operation is performed directly on the original DataFrame, and the function returns None.

When inplace=False (default), the function returns a new modified DataFrame, and the original DataFrame remains unchanged.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})

# Using inplace = False (default)
df2 = df.drop('A', axis=1)
print("Original DataFrame:")
print(df)

print("\nNew DataFrame:")
print(df2)

#Now Using inplace=True

df.drop('A', axis=1, inplace=True)
print(df)

Original DataFrame:
   A  B
0  1  4
1  2  5
2  3  6

New DataFrame:
   B
0  4
1  5
2  6
   B
0  4
1  5
2  6


Important Interview Note

In modern Pandas usage, many developers prefer not using inplace=True because:

It does not always provide performance benefits.

It can sometimes make debugging harder.

Chaining operations becomes easier when returning a new DataFrame.

# **5.How can you change the index of a DataFrame in Python (Pandas)? Explain the method used.**

In Pandas, you can change the index of a DataFrame using the set_index() method.

🔹 Syntax:
DataFrame.set_index(keys, drop=True, append=False, inplace=False, verify_integrity=False)
🔹 Explanation of Important Parameters:

keys: Column name(s) or array-like object(s) to set as the new index.
This can be:

A single column name

A list of column names (for multi-index)

An array, Series, or NumPy array of the same length as the DataFrame

drop (default = True):
Removes the column(s) used as the index from the DataFrame.

inplace (default = False):
If True, modifies the original DataFrame. Otherwise, returns a new DataFrame.

append (default = False):
If True, adds the new index to the existing index instead of replacing it.

verify_integrity (default = False):
Checks for duplicate index values.

In [ ]:
# Example 1: Setting a Single Column as Index

import pandas as pd

df = pd.DataFrame({
    'ID': [101, 102, 103],
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Score': [85, 90, 95]
})

df_new = df.set_index('ID')
print(df_new)

#Example 2: Changing Index Using inplace=True

df.set_index('Name', inplace=True)
print(df)

#Example 3: Setting Multiple Columns (MultiIndex)

df = pd.DataFrame({
    'Department': ['IT', 'IT', 'HR'],
    'Employee': ['A', 'B', 'C'],
    'Salary': [50000, 60000, 45000]
})

df_multi = df.set_index(['Department', 'Employee'])
print(df_multi)

        Name  Score
ID                 
101    Alice     85
102      Bob     90
103  Charlie     95
          ID  Score
Name               
Alice    101     85
Bob      102     90
Charlie  103     95
                     Salary
Department Employee        
IT         A          50000
           B          60000
HR         C          45000


# **6.How can you check whether a number is prime or not in Python?**


A prime number is a number greater than 1 that is divisible only by 1 and itself.

To check whether a number is prime in Python, we test if it is divisible by any number other than 1 and itself. If it is divisible by any other number, it is not prime.

In [ ]:
num = int(input("Enter any number: "))

if num > 1:
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            print(num, "is not a prime number")
            break
    else:
        print(num, "is a prime number")
else:
    print(num, "is not a prime number")

    #Why use int(num**0.5) + 1?

#We only need to check divisibility up to the square root of the number. This makes the solution more efficient.

Enter any number: 19
19 is a prime number


# **7.What is the difference between univariate and bivariate analysis? Also, which Python functions are commonly used to perform each type of analysis?**

# **Univariate Analysis**

Univariate analysis involves analyzing a single variable at a time.
It is used to understand the distribution, central tendency, and spread of the data.

Common objectives:

Understand distribution

Detect outliers

Measure mean, median, variance, etc.

Common Python functions and libraries:

df.describe()

df['column'].mean()

df['column'].median()

df['column'].value_counts()

df['column'].std()

df['column'].plot(kind='hist')

sns.histplot()

sns.boxplot()

**🔹 Bivariate Analysis**

Bivariate analysis involves analyzing two variables simultaneously to understand the relationship between them.

Common objectives:

Measure correlation

Identify trends

Compare categories

Common Python functions and libraries:

df.corr()

sns.scatterplot()

sns.lineplot()

sns.boxplot(x= , y= )

sns.barplot()

pd.crosstab()

plt.scatter()

# **8.How does a for loop differ from a while loop in Python? Explain with examples.**


Both for and while loops are used to execute a block of code repeatedly, but they differ in how the repetition is controlled.

🔹 for Loop

A for loop is used when the number of iterations is known in advance or when iterating over a sequence (such as a list, tuple, string, or range).


while Loop

A while loop is used when the number of iterations is not known beforehand. It runs as long as a given condition is True.

In [ ]:
for i in range(5):
    print(i)


0
1
2
3
4


In [ ]:

# While loop
count = 0
while count < 5:
    print(count)
    count += 1

0
1
2
3
4


# **9.How can you import multiple Excel sheets into a single DataFrame in Python? Explain with an example.**

In Python, you can use the pd.read_excel() function from the Pandas library to read multiple sheets from an Excel file.

If you want to load all sheets at once, you can set the parameter sheet_name=None. This returns a dictionary where:

Keys → Sheet names

Values → Corresponding DataFrames

You can then combine all sheets into a single DataFrame using pd.concat().



In [ ]:
import pandas as pd

# Read all sheets from the Excel file
excel_file = pd.read_excel("data.xlsx", sheet_name=None)

# Combine all sheets into one DataFrame
df = pd.concat(excel_file.values(), ignore_index=True)

print(df)



#Explanation

sheet_name=None → Reads all sheets.

excel_file.values() → Extracts all DataFrames from the dictionary.

pd.concat(..., ignore_index=True) → Combines them into one DataFrame and resets the index.




In [ ]:
#If You Want Specific Sheets Only:

df = pd.concat(
    pd.read_excel("data.xlsx", sheet_name=["Sheet1", "Sheet2"]),
    ignore_index=True
)

# **Interview Tip for Question 9:**

sheet_name=None → Load all sheets.

sheet_name="Sheet1" → Load one sheet.

sheet_name=["Sheet1","Sheet2"] → Load selected sheets.

# **10.What is the difference between the append() and extend() methods in Python lists? Explain with examples.**



Both append() and extend() are list methods in Python used to add elements to a list. However, they work differently.

🔹 append() Method

The append() method adds a single element to the end of the list.
If you append a list, the entire list is added as one element.

Syntax:
list.append(item)


In [ ]:
list1 = [1, 2, 3]
list1.append([4, 5])

print(list1)

[1, 2, 3, [4, 5]]


Here, [4, 5] is added as a single element.

**extend() Method**

The extend() method adds each element of an iterable (like a list, tuple, or string) to the list individually.

Syntax:
list.extend(iterable)
Example:

In [ ]:
list2 = [1, 2, 3]
list2.extend([4, 5])

print(list2)

[1, 2, 3, 4, 5]


| `append()`                      | `extend()`                                        |
| ------------------------------- | ------------------------------------------------- |
| Adds one element                | Adds multiple elements                            |
| Can add a list as a single item | Adds elements of the list individually            |
| Increases list length by 1      | Increases list length by number of elements added |


# **11.What are the different built-in data types available in Python?**


Python provides several built-in data types that are used to store different kinds of data. These data types can be grouped into the following categories:

🔹 Numeric Types

Used to store numerical values.

int – Integer values (e.g., 10, 25)

float – Decimal numbers (e.g., 3.14, 2.5)

complex – Complex numbers (e.g., 2 + 3j)


🔹 Sequence Types

Used to store ordered collections of items.

list – Ordered and mutable collection (e.g., [1, 2, 3])

tuple – Ordered but immutable collection (e.g., (1, 2, 3))

string – Sequence of characters (e.g., "Python")

🔹 Set Type

Used to store unordered unique elements.

set – Example: {1, 2, 3}

🔹 Mapping Type

Used to store key-value pairs.

dictionary (dict) – Example: {"name": "John", "age": 25}


🔹 Boolean Type

Represents logical values.

bool – True or False

In [1]:
num = 10              # int
price = 5.99          # float
name = "Python"       # string
numbers = [1, 2, 3]   # list
data = {"a": 1}       # dictionary
flag = True           # boolean

In [2]:
# Numeric data types
num = 10              # int
price = 5.99          # float

# Sequence data types
name = "Python"       # string
numbers = [1, 2, 3]   # list
coordinates = (10, 20) # tuple

# Mapping type
data = {"a": 1, "b": 2}  # dictionary

# Set type
unique_values = {1, 2, 3}

# Boolean type
flag = True           # boolean

# Print values and their types
print(num, type(num))
print(price, type(price))
print(name, type(name))
print(numbers, type(numbers))
print(coordinates, type(coordinates))
print(data, type(data))
print(unique_values, type(unique_values))
print(flag, type(flag))

10 <class 'int'>
5.99 <class 'float'>
Python <class 'str'>
[1, 2, 3] <class 'list'>
(10, 20) <class 'tuple'>
{'a': 1, 'b': 2} <class 'dict'>
{1, 2, 3} <class 'set'>
True <class 'bool'>


# **12.How can you write a Python function to detect and handle outliers in a dataset? Explain using the Interquartile Range (IQR) method with an example**

Outliers are extreme values that differ significantly from other values in a dataset.
One common method to detect outliers is the Interquartile Range (IQR) method.

IQR Formula



IQR=Q3−Q1

Where:

Q1 = 25th percentile

Q3 = 75th percentile

Outliers are defined as values outside the range:


[Q1−1.5×IQR,Q3+1.5×IQR]

We can write a Python function to remove or filter out outliers using this rule.

In [3]:
#Python Function to Remove Outliers

import numpy as np

def remove_outliers(data, multiplier=1.5):

    a = np.array(data)

    Q1 = np.percentile(a, 25)
    Q3 = np.percentile(a, 75)

    IQR = Q3 - Q1

    lower_bound = Q1 - multiplier * IQR
    upper_bound = Q3 + multiplier * IQR

    result = [x for x in a if lower_bound <= x <= upper_bound]

    return result

In [4]:
data = [10, 12, 14, 15, 18, 20, 100]

clean_data = remove_outliers(data)

print("Original Data:", data)
print("Data without outliers:", clean_data)

Original Data: [10, 12, 14, 15, 18, 20, 100]
Data without outliers: [np.int64(10), np.int64(12), np.int64(14), np.int64(15), np.int64(18), np.int64(20)]


# **Interview Tip:**

Outliers can also be handled by:

Removing them

Replacing with median or mean

Capping (Winsorization)

Using transformation techniques

In real-world data science projects, capping or imputing is often preferred instead of removing data.

# **13.Can any type of string be converted into an integer in Python? Explain with an example.**



In Python, the int() function is used to convert a value into an integer. However, not all strings can be converted into integers.

A string can be converted to an integer only if it contains numeric characters (for example "10" or "25"). If the string contains non-numeric characters (such as "abc"), Python will raise a ValueError.

If a floating-point number is passed to int(), Python converts it to an integer by removing the fractional part (it does not round; it truncates).

In [5]:
#Example 1: Converting a Numeric String

num_str = "25"

num = int(num_str)

print(num)
print(type(num))


25
<class 'int'>


In [6]:
#Example 2: Converting a Float to an Integer

value = 10.8

num = int(value)

print(num)

10


In [ ]:
#Example 3: Invalid Conversion

text = "hello"

num = int(text)
#This happens because "hello" is not a numeric string.-- you will get an error

# **14.How can you check whether a number is an Armstrong number in Python? Explain with an example.**


An Armstrong number is a number that is equal to the sum of the powers of its digits.

For example:

153 is an Armstrong number because:

1³ + 5³ + 3³ = 153

To check if a number is an Armstrong number in Python, we extract each digit, raise it to the power of the number of digits, and then add the results. If the sum equals the original number, it is an Armstrong number.



In [11]:
# Python program to check if a number is an Armstrong number

num = int(input("Enter a number: "))

sum_of_digits = 0
temp = num

# number of digits
power = len(str(num))

while temp > 0:
    digit = temp % 10
    sum_of_digits += digit ** power
    temp //= 10

if num == sum_of_digits:
    print(num, "is an Armstrong number")
else:
    print(num, "is not an Armstrong number")

Enter a number: 143
143 is not an Armstrong number


Key Idea

Steps used in the algorithm:

Count the number of digits.

Extract each digit using % 10.

Raise the digit to the power of the number of digits.

Add the results.

Compare the sum with the original number.

# **15.Can you list the  difference between a list, array, and tuple in Python? Explain with examples.**


In Python, lists, arrays, and tuples are used to store collections of data. However, they differ in terms of mutability, data types, and usage.

🔹 List

A list is an ordered and mutable collection of elements.
Lists can store different data types such as integers, strings, and floats.

Lists are defined using square brackets [], and elements can be accessed using their index.

In [12]:
# List example
my_list = [10, "Python", 3.5]

print(my_list)
print(my_list[1])   # Access element by index

# Lists are mutable
my_list[0] = 20
print(my_list)

[10, 'Python', 3.5]
Python
[20, 'Python', 3.5]


🔹 Array

An array is an ordered collection of elements that usually contain elements of the same data type.
Arrays are mutable and elements can be accessed using an index.

In Python, arrays are commonly created using NumPy.

In [13]:
import numpy as np

# Array example
arr = np.array([1, 2, 3, 4])

print(arr)
print(arr[2])   # Access element

[1 2 3 4]
3


🔹 Tuple

A tuple is an ordered collection of elements that is immutable (cannot be changed after creation).
Tuples can store different data types and are defined using parentheses ().

In [14]:
# Tuple example
my_tuple = (10, "Python", 3.5)

print(my_tuple)
print(my_tuple[0])

# This will cause an error because tuples are immutable
# my_tuple[0] = 20

(10, 'Python', 3.5)
10


🔎 Key Differences

| Feature     | List                      | Array                           | Tuple                     |
| ----------- | ------------------------- | ------------------------------- | ------------------------- |
| Mutability  | Mutable                   | Mutable                         | Immutable                 |
| Data types  | Can store different types | Usually same type               | Can store different types |
| Syntax      | `[ ]`                     | `np.array()`                    | `( )`                     |
| Performance | Moderate                  | Faster for numerical operations | Faster than lists         |






🧠 Interview Tip

Lists → general-purpose data storage

Arrays → numerical computations (NumPy, ML, data science)

Tuples → fixed data that should not change