<a href="https://colab.research.google.com/github/Gitstrong3333/Data-Science-Interview/blob/main/MachineLearning_Interview_Questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Please focus on learning Machine Learning. If you have worked on Python and Machine Learning projects, review the material regularly.

**I will be updating 5 questions daily based on the topics I study.**

# **Ace Your Upcoming Data Science Interview**

You may not be able to predict every question an interviewer will ask. However, you can prepare for many of the most important and frequently asked technical questions in advance.

This repository has been carefully curated to support your preparation for technical interview rounds. It is designed to strengthen your understanding of core data science concepts and help you confidently approach data science job opportunities.

# **Which function is commonly used to convert a multidimensional NumPy array into a one-dimensional array? If the resulting array is modified, will it affect the original array? Explain your answer.**

The flatten() function in NumPy is commonly used to convert a multidimensional array into a one-dimensional array.

The flatten() method returns a copy of the original array. Therefore, if you modify the flattened array, it will not affect the original array.

In [ ]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original Array:")
print(arr)

# Convert to 1D using flatten()
flat_arr = arr.flatten()

print("\nFlattened Array:")
print(flat_arr)

# Modify flattened array
flat_arr[0] = 100

print("\nModified Flattened Array:")
print(flat_arr)

print("\nOriginal Array After Modification:")
print(arr)

Original Array:
[[1 2 3]
 [4 5 6]]

Flattened Array:
[1 2 3 4 5 6]

Modified Flattened Array:
[100   2   3   4   5   6]

Original Array After Modification:
[[1 2 3]
 [4 5 6]]


# **2.If two variables are defined as a = 3 and b = 4, will the id() function return the same value for both variables? Explain your answer.**



Answer: Rewritten Answer

No, the id() function will not return the same value for a and b.

In Python, the id() function returns the unique identity of an object, which typically corresponds to its memory address. Since 3 and 4 are two different integer objects, they have different identities in memory. Therefore, id(a) and id(b) will return different values.

Each object in Python has a unique identity that remains constant during its lifetime.

In [1]:
a = 3
b = 4

print(id(a))
print(id(b))

11654440
11654472


# **3.If two variables are defined as mean = 8 and Mean = 8, are they considered the same variable in Python? Explain your answer.**


No, mean and Mean are not considered the same variable in Python.

Python is a case-sensitive programming language, which means it treats uppercase and lowercase letters as different characters. Therefore, variable names that differ only in case are treated as completely separate variables.

Even though both variables store the same value (8), they are distinct identifiers in memory.

In [2]:
mean = 8
Mean = 8

print(mean)
print(Mean)

8
8


Both will print 7, but they are two different variables.

# **4.What is the purpose of the inplace parameter in Pandas functions? Explain its behavior.**


The inplace parameter in Pandas functions determines whether a DataFrame is modified directly or a modified copy is returned.

When inplace=True, the operation is performed directly on the original DataFrame, and the function returns None.

When inplace=False (default), the function returns a new modified DataFrame, and the original DataFrame remains unchanged.

In [3]:
import pandas as pd

df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})

# Using inplace = False (default)
df2 = df.drop('A', axis=1)
print("Original DataFrame:")
print(df)

print("\nNew DataFrame:")
print(df2)

#Now Using inplace=True

df.drop('A', axis=1, inplace=True)
print(df)

Original DataFrame:
   A  B
0  1  4
1  2  5
2  3  6

New DataFrame:
   B
0  4
1  5
2  6
   B
0  4
1  5
2  6


Important Interview Note

In modern Pandas usage, many developers prefer not using inplace=True because:

It does not always provide performance benefits.

It can sometimes make debugging harder.

Chaining operations becomes easier when returning a new DataFrame.

# **5.How can you change the index of a DataFrame in Python (Pandas)? Explain the method used.**

In Pandas, you can change the index of a DataFrame using the set_index() method.

🔹 Syntax:
DataFrame.set_index(keys, drop=True, append=False, inplace=False, verify_integrity=False)
🔹 Explanation of Important Parameters:

keys: Column name(s) or array-like object(s) to set as the new index.
This can be:

A single column name

A list of column names (for multi-index)

An array, Series, or NumPy array of the same length as the DataFrame

drop (default = True):
Removes the column(s) used as the index from the DataFrame.

inplace (default = False):
If True, modifies the original DataFrame. Otherwise, returns a new DataFrame.

append (default = False):
If True, adds the new index to the existing index instead of replacing it.

verify_integrity (default = False):
Checks for duplicate index values.

In [5]:
# Example 1: Setting a Single Column as Index

import pandas as pd

df = pd.DataFrame({
    'ID': [101, 102, 103],
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Score': [85, 90, 95]
})

df_new = df.set_index('ID')
print(df_new)

#Example 2: Changing Index Using inplace=True

df.set_index('Name', inplace=True)
print(df)

#Example 3: Setting Multiple Columns (MultiIndex)

df = pd.DataFrame({
    'Department': ['IT', 'IT', 'HR'],
    'Employee': ['A', 'B', 'C'],
    'Salary': [50000, 60000, 45000]
})

df_multi = df.set_index(['Department', 'Employee'])
print(df_multi)

        Name  Score
ID                 
101    Alice     85
102      Bob     90
103  Charlie     95
          ID  Score
Name               
Alice    101     85
Bob      102     90
Charlie  103     95
                     Salary
Department Employee        
IT         A          50000
           B          60000
HR         C          45000
